### ISSUE TITLE
[feature] Support for windows, Support for config file

### ISSUE THREAD

**Issue by XQDD** [xelabs/go-mydumper#16]
#### Config file example([yml format](https://github.com/go-yaml/yaml)):
```yml
db-dump-out:
  host: xxx
  port: xxx
  user: xxx
  password: xxx
  db-name: xxx
  table-name: xxx

db-load-in:
  host: xxx
  port: xxx
  user: xxx
  password: xxx
  db-name: xxx
  table-name: xxx
```

#### Windows' Problem
[xlog problem](https://stackoverflow.com/questions/42083059/getting-syslog-writer-undefined)
```cmd
F:\code\go\src\github.com\xelabs\go-mydumper\src\mystreamer>go install
# github.com/xelabs/go-mysqlstack/xlog
..\..\..\go-mysqlstack\xlog\xlog.go:66:12: undefined: syslog.New
..\..\..\go-mysqlstack\xlog\xlog.go:66:23: undefined: syslog.LOG_DEBUG
```
